# Generated by Django 5.2.8 on 2025-11-13 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVoz',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('voice_code_tts', models.CharField(default='en-US-Wavenet-F', max_length=50)),
                ('velocidad', models.FloatField(default=1.0)),
                ('idioma_preferido', models.CharField(default='en-US', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('idioma_actual', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('contenido_texto', models.TextField()),
                ('audio_url', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroError',
            fields=[
                ('id_error', models.AutoField(primary_key=True, serialize=False)),
                ('texto_original', models.TextField()),
                ('texto_corregido', models.TextField()),
                ('explicacion_regla', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
