# Generated by Django 5.2.8 on 2025-12-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='configuracionvoz',
            name='idioma_preferido',
            field=models.CharField(default='es-US', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracionvoz',
            name='voice_code_tts',
            field=models.CharField(default='es-US-Wavenet-A', max_length=50),
        ),
    ]
