# Generated by Django 5.2.8 on 2025-12-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_progresousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresousuario',
            name='mostrar_gamificacion',
            field=models.BooleanField(default=True, verbose_name='Ver Gamificación en Chat'),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='publico_en_leaderboard',
            field=models.BooleanField(default=True, verbose_name='Aparecer en Ranking Global'),
        ),
    ]
