# Generated by Django 5.2.8 on 2026-01-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_errorpronunciacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpronunciacion',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conversacion'),
        ),
    ]
