# Generated by Django 5.2.8 on 2026-01-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_errorpronunciacion_conversacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresousuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='progresousuario',
            name='cuenta_verificada',
            field=models.BooleanField(default=False),
        ),
    ]
