# Generated by Django 5.2.8 on 2026-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionvoz',
            name='idioma_nativo',
            field=models.CharField(default='Español', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionvoz',
            name='idioma_objetivo',
            field=models.CharField(default='Inglés', max_length=50),
        ),
    ]
