# Generated by Django 5.2.8 on 2026-02-06 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracionvoz_idioma_nativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('traduccion', models.CharField(max_length=150)),
                ('ejemplo', models.TextField(blank=True, null=True)),
                ('nivel_dominio', models.IntegerField(default=0)),
                ('proximo_repaso', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_repaso', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
