# Generated by Django 5.2.8 on 2026-02-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vocabulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulario',
            name='idioma_palabra',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
