# Generated by Django 5.2.8 on 2026-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vocabulario_idioma_palabra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='categoria_seguridad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='confianza_seguridad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='es_toxico',
            field=models.BooleanField(default=False),
        ),
    ]
