# Generated by Django 5.2.8 on 2026-02-19 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mensaje_categoria_seguridad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('idioma_tag', models.CharField(max_length=50)),
                ('num_preguntas', models.IntegerField(default=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntentoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('disponible_desde', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quiz', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('pregunta', models.TextField()),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(max_length=255)),
                ('opcion_d', models.CharField(max_length=255)),
                ('respuesta_correcta', models.IntegerField()),
                ('explicacion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('vocabulario', 'Vocabulario'), ('gramatica', 'Gramática'), ('conjugacion', 'Conjugación'), ('comprension', 'Comprensión')], default='vocabulario', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.quiz')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_usuario', models.IntegerField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.intentoquiz')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizpregunta')),
            ],
        ),
    ]
