# Generated by Django 5.2.8 on 2026-02-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quiz_intentoquiz_quizpregunta_respuestaintento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionvoz',
            name='dias_cooldown',
            field=models.IntegerField(default=3, verbose_name='Días de espera para repetir Quizzes'),
        ),
        migrations.AlterField(
            model_name='quizpregunta',
            name='categoria',
            field=models.CharField(choices=[('vocabulario', 'Vocabulario'), ('gramatica', 'Gramática'), ('conjugacion', 'Conjugación')], default='vocabulario', max_length=20),
        ),
    ]
