# Generated by Django 5.2.8 on 2026-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionvoz',
            name='voice_code_native_tts',
            field=models.CharField(default='es-ES-Neural2-B', max_length=50, verbose_name='Voz Idioma Nativo'),
        ),
        migrations.AlterField(
            model_name='configuracionvoz',
            name='voice_code_tts',
            field=models.CharField(default='es-US-Wavenet-A', max_length=50, verbose_name='Voz Idioma Objetivo'),
        ),
    ]
